### ISSUE TITLE
setBackgroundColor doesn't work

### ISSUE THREAD

**Issue by colasbd** [gloubibou/HHRoundedBox#1]
Hi, 
thanks for HHRoundedBox.
It seems to me that changing the background color doesn't work.

(I am new to the github community so I don't know the rules. I hope it is fair to tell you that in this way)

**Comment by colasbd** [comment]
It's ok. 

J'ai compris. Il fallait self.box.drawsGradientBackground = NO ;

Comment fait-on pour faire un pull roquets ?
J'ai une proposition de petite modif' pour ta classe et je voudrais apprendre à participer à un projet github.

Merci !

**Comment by gloubibou** [comment]
Bonjour.

Il faut faire un fork sur GitHub. Modifier le fork (ou un clone sur la machine locale).

**Comment by colasbd** [comment]
Bonjour,

Est-ce que sur le fork je peux rester sur la branche master (origine/master) ou bien est-ce qu'il faut que je crée une branche avec ma modif ?

merci !
J'ai vu que tu as accepté ma modif, c'est super !

Colas

---

 De : Pierre Bernard notifications@github.com
À : gloubibou/HHRoundedBox HHRoundedBox@noreply.github.com 
Cc : colasjojo colasjojo@yahoo.fr 
Envoyé le : Jeudi 10 octobre 2013 15h41
Objet : Re: [HHRoundedBox] setBackgroundColor doesn't work (#1)

Bonjour.
Il faut faire un fork sur GitHub. Modifier le fork (ou un clone sur la machine locale).

**Comment by gloubibou** [comment]
Je ne vois pas de problème à rester sur la branche master.
Je crois qu’une branche pourrait devenir utile pour créer un pull request limité à un changement en particulier.

Cela dit, je suis très loin d’être expert sur git. Pour mes projets j’utilise et préfère SVN

**Comment by colasbd** [comment]
Merci !

---

 De : Pierre Bernard notifications@github.com
À : gloubibou/HHRoundedBox HHRoundedBox@noreply.github.com 
Cc : colasjojo colasjojo@yahoo.fr 
Envoyé le : Vendredi 11 octobre 2013 21h50
Objet : Re: [HHRoundedBox] setBackgroundColor doesn't work (#1)

Je ne vois pas de problème à rester sur la branche master. 
Je crois qu’une branche pourrait devenir utile pour créer un pull request limité à un changement en particulier. 

Cela dit, je suis très loin d’être expert sur git. Pour mes projets j’utilise et préfère SVN
